

response = {
  "file.pdf":{
    "1":{
      "FUNCTIONAL_NAME":[
        {
          "en":"MULTIPACK DIPS - TEX MEX SELECTION D"
        },
        {
          "en":"A multipack of dips comprising of: Sour Cream and Chive, Nacho Chilli Cheese, Guacamole and Tomato Salsa"
        }
      ],
      "GTIN_HEADER":[
        {
          "en":"4088600282848"
        }
      ],
      "UNMAPPED":[
        {
          "en":"ZORBA DELICACIES LTD"
        },
        {
          "en":"FOP: Use By: QR code, Keep refrigerated below 5°C"
        },
        {
          "en":"289.000000"
        },
        {
          "en":"18073"
        },
        {
          "en":"709102"
        },
        {
          "en":"403074"
        },
        {
          "en":"No"
        },
        {
          "en":"N/A"
        },
        {
          "en":"N/A"
        },
        {
          "en":"Yes"
        }
      ],
      "BRAND_NAME":[
        {
          "en":"THE DELI"
        }
      ],
      "GENERIC_NAME":[
        {
          "mt":"Tex Mex Multipack"
        }
      ],
      "NET_CONTENT_STATEMENT":[
        {
          "en":"400g"
        }
      ],
      "OTHER_INSTRUCTIONS":[
        {
          "en":"Front, bottom right hand corner of pack."
        }
      ],
      "STORAGE_INSTRUCTIONS":[
        {
          "en":"Keep refrigerated below 5°C."
        },
        {
          "en":"Once opened, consume immediately."
        }
      ]
    },
    "2":{
      "UNMAPPED":[
        {
          "en":"Not suitable for freezing."
        },
        {
          "en":"N/A"
        },
        {
          "en":"N/A"
        },
        {
          "en":"Packaged in a protective atmosphere."
        },
        {
          "pl":"Tray: Recycle / Sleeve: Recycle / Film: Don't Recycle /"
        },
        {
          "en":"PTR96 Multipack Tray (No); PES28 Multipack Film (No); 105670 Sleeve (No);"
        }
      ],
      "MARKETING_CLAIM":[
        {
          "en":"N/A"
        },
        {
          "en":"FSC/PEFC"
        },
        {
          "en":"No artificial colours or flavourings."
        },
        {
          "is":"Chilli Rating - Mild (One Chilli Symbol) (Nacho Chilli Cheese Pot)."
        },
        {
          "en":"Suitable for vegetarians (text only)."
        },
        {
          "en":"Suitable for vegetarians (Aldi logo)."
        },
        {
          "en":"new look, improved recipe."
        },
        {
          "en":"Packaged in a protective atmosphere."
        }
      ]
    },
    "3":{
      "ALLERGEN_STATEMENT":[
        {
          "nl":"For allergens, see ingredients in &lt;b&gt;bold&lt;/b&gt;."
        },
        {
          "en":"Recipe Allergens not pulling through - Contains egg and milk."
        }
      ],
      "FUNCTIONAL_NAME":[
        {
          "en":"MULTIPACK DIPS - TEX MEX SELECTION D"
        }
      ],
      "GTIN_HEADER":[
        {
          "en":"4088600282848"
        }
      ],
      "UNMAPPED":[
        {
          "en":"ZORBA DELICACIES LTD"
        },
        {
          "en":"EPD"
        },
        {
          "en":"289.000000"
        },
        {
          "en":"18073"
        }
      ],
      "NUTRITION_FACTS":[
        {
          "Energy":[
            {
              "Value":{
                "en":"1010"
              }
            },
            {
              "Value":{
                "en":"505"
              }
            },
            {
              "Value":{
                "en":"245"
              }
            },
            {
              "Value":{
                "en":"122"
              }
            },
            {
              "Value":{
                "en":"505kJ\r122kcal"
              }
            },
            {
              "PDV":{
                "en":"6%"
              }
            }
          ],
          "Fat":[
            {
              "Value":{
                "en":"23.8"
              }
            },
            {
              "Value":{
                "en":"11.9"
              }
            },
            {
              "Value":{
                "en":"11.9g"
              }
            },
            {
              "PDV":{
                "en":"17%"
              }
            }
          ],
          "Saturated Fat":[
            {
              "Value":{
                "en":"7.7"
              }
            },
            {
              "Value":{
                "en":"3.9"
              }
            },
            {
              "Value":{
                "en":"3.9g"
              }
            },
            {
              "PDV":{
                "en":"19%"
              }
            }
          ],
          "Carbohydrate":[
            {
              "Value":{
                "en":"5.4"
              }
            },
            {
              "Value":{
                "en":"2.7"
              }
            }
          ],
          "Sugar":[
            {
              "Value":{
                "en":"2.2"
              }
            },
            {
              "Value":{
                "en":"1.1"
              }
            },
            {
              "Value":{
                "en":"1.1g"
              }
            },
            {
              "PDV":{
                "en":"1%"
              }
            }
          ],
          "Fibre":[
            {
              "Value":{
                "en":"0.5"
              }
            },
            {
              "Value":{
                "en":"0.2"
              }
            }
          ],
          "Protein":[
            {
              "Value":{
                "en":"2.0"
              }
            },
            {
              "Value":{
                "en":"1.0"
              }
            }
          ],
          "Salt":[
            {
              "Value":{
                "en":"0.83"
              }
            },
            {
              "Value":{
                "en":"0.42"
              }
            },
            {
              "Value":{
                "en":"0.42g"
              }
            },
            {
              "PDV":{
                "en":"7%"
              }
            }
          ]
        }
      ]
    },
    "4":{
      "UNMAPPED":[
        {
          "en":"709102"
        },
        {
          "en":"403092"
        },
        {
          "en":"No"
        },
        {
          "en":"N/A"
        },
        {
          "en":"N/A"
        },
        {
          "en":"No"
        },
        {
          "en":"N/A"
        },
        {
          "en":"N/A"
        },
        {
          "en":"N/A"
        },
        {
          "en":"Packaged in a protective atmosphere."
        },
        {
          "pl":"Tray: Recycle / Sleeve: Recycle / Film: Don't Recycle /"
        }
      ],
      "BRAND_NAME":[
        {
          "en":"THE DELI"
        }
      ],
      "GENERIC_NAME":[
        {
          "en":"Guacamole"
        }
      ],
      "FUNCTIONAL_NAME":[
        {
          "en":"Avocado dip with onion, red chilli and coriander"
        }
      ],
      "NET_CONTENT_STATEMENT":[
        {
          "en":"100g"
        }
      ],
      "OTHER_INSTRUCTIONS":[
        {
          "en":"Front, bottom right hand corner of pack."
        }
      ],
      "STORAGE_INSTRUCTIONS":[
        {
          "en":"Keep refrigerated below 5°C."
        },
        {
          "en":"Once opened, consume immediately."
        }
      ],
      "MARKETING_CLAIM":[
        {
          "en":"N/A"
        },
        {
          "en":"No artificial colours or flavourings."
        },
        {
          "en":"new look, improved recipe."
        },
        {
          "en":"Suitable for vegetarians (Aldi logo)."
        },
        {
          "en":"Suitable for vegetarians (text only)"
        },
        {
          "en":"FSC/PEFC"
        }
      ],
      "WARNING_STATEMENTS":[
        {
          "en":"Packaged in a protective atmosphere."
        }
      ]
    },
    "5":{
      "UNMAPPED":[
        {
          "en":"PTR96 Multipack Tray (No); PES28 Multipack Film (No); 105670 Sleeve (No);"
        },
        {
          "en":"ZORBA DELICACIES LTD"
        },
        {
          "en":"FOP: Use By: QR code, Keep refrigerated below 5°C"
        },
        {
          "en":"289.000000"
        },
        {
          "en":"18073"
        },
        {
          "en":"709102"
        }
      ],
      "INGREDIENTS_DECLARATION":[
        {
          "fr":"AVOCADO PURÉE (45%), AVOCADO (29%), Water, ONIONS (8%), Concentrated Lime Juice, Garlic Purée, Sugar, Red Chilli, Coriander, Salt, Antioxidants: Ascorbic Acid; Acidity Regulators: Citric Acid; Stabiliser: Xanthan Gum; Preservative: Potassium Sorbate."
        }
      ],
      "ALLERGEN_STATEMENT":[
        {
          "en":"Not Applicable"
        }
      ],
      "FUNCTIONAL_NAME":[
        {
          "en":"MULTIPACK DIPS - TEX MEX SELECTION D"
        }
      ],
      "GTIN_HEADER":[
        {
          "en":"4088600282848"
        }
      ],
      "NUTRITION_FACTS":[
        {
          "Energy":[
            {
              "Value":{
                "en":"491"
              }
            },
            {
              "Value":{
                "en":"246"
              }
            },
            {
              "Value":{
                "en":"119"
              }
            },
            {
              "Value":{
                "en":"60"
              }
            },
            {
              "PDV":{
                "en":"3%"
              }
            }
          ],
          "Fat":[
            {
              "Value":{
                "en":"10.5"
              }
            },
            {
              "Value":{
                "en":"5.2"
              }
            },
            {
              "PDV":{
                "en":"7%"
              }
            }
          ],
          "Saturated Fat":[
            {
              "Value":{
                "en":"2.4"
              }
            },
            {
              "Value":{
                "en":"1.2"
              }
            },
            {
              "PDV":{
                "en":"6%"
              }
            }
          ],
          "Carbohydrate":[
            {
              "Value":{
                "en":"2.7"
              }
            },
            {
              "Value":{
                "en":"1.3"
              }
            }
          ],
          "Sugar":[
            {
              "Value":{
                "en":"2.2"
              }
            },
            {
              "Value":{
                "en":"1.1"
              }
            },
            {
              "PDV":{
                "en":"1%"
              }
            }
          ],
          "Fibre":[
            {
              "Value":{
                "en":"4.5"
              }
            },
            {
              "Value":{
                "en":"2.3"
              }
            }
          ],
          "Protein":[
            {
              "Value":{
                "en":"1.3"
              }
            },
            {
              "Value":{
                "en":"0.7"
              }
            }
          ],
          "Salt":[
            {
              "Value":{
                "en":"0.57"
              }
            },
            {
              "Value":{
                "en":"0.28"
              }
            },
            {
              "PDV":{
                "en":"5%"
              }
            }
          ]
        }
      ]
    },
    "6":{
      "UNMAPPED":[
        {
          "en":"403093"
        },
        {
          "en":"No"
        },
        {
          "en":"N/A"
        },
        {
          "en":"N/A"
        },
        {
          "en":"No"
        },
        {
          "en":"Not suitable for freezing."
        },
        {
          "en":"N/A"
        },
        {
          "en":"N/A"
        },
        {
          "pl":"Tray: Recycle / Sleeve: Recycle / Film: Don't Recycle /"
        },
        {
          "en":"PTR96 Multipack Tray (No); PES28 Multipack Film (No); 105670 Sleeve (No);"
        }
      ],
      "BRAND_NAME":[
        {
          "en":"THE DELI"
        }
      ],
      "GENERIC_NAME":[
        {
          "en":"Sour Cream & Chive Dip"
        }
      ],
      "FUNCTIONAL_NAME":[
        {
          "en":"A soured cream and mayonnaise dip with chives"
        }
      ],
      "NET_CONTENT_STATEMENT":[
        {
          "en":"100g"
        }
      ],
      "OTHER_INSTRUCTIONS":[
        {
          "en":"Front, bottom right hand corner of pack."
        }
      ],
      "STORAGE_INSTRUCTIONS":[
        {
          "en":"Keep refrigerated below 5°C."
        },
        {
          "en":"Once opened, keep refrigerated and consume within 2 days and by date shown."
        }
      ],
      "MARKETING_CLAIM":[
        {
          "en":"N/A"
        },
        {
          "en":"No artificial colours or flavourings."
        },
        {
          "en":"FSC/PEFC"
        },
        {
          "en":"Suitable for vegetarians (Aldi logo)."
        },
        {
          "en":"Suitable for vegetarians (text only)."
        },
        {
          "en":"new look, improved recipe."
        }
      ]
    },
    "7":{
      "INGREDIENTS_DECLARATION":[
        {
          "en":"SOURED CREAM (56%) (&lt;b&gt;Milk&lt;/b&gt;), MAYONNAISE (28%) [Water, Rapeseed Oil, Spirit Vinegar, Whole &lt;b&gt;Egg&lt;/b&gt; Powder, Maize Starch, Sugar, Salt, Citrus Fibre, Rice Starch, &lt;b&gt;Egg&lt;/b&gt; White Powder, Sucrose, Potato Fibre], Onions, CHIVES (3.5%), Cornflour, Rapeseed Oil, Concentrated Lemon Juice, Salt, Preservative: Potassium Sorbate."
        }
      ],
      "ALLERGEN_STATEMENT":[
        {
          "nl":"For allergens, see ingredients in &lt;b&gt;bold&lt;/b&gt;."
        }
      ],
      "FUNCTIONAL_NAME":[
        {
          "en":"MULTIPACK DIPS - TEX MEX SELECTION D"
        }
      ],
      "GTIN_HEADER":[
        {
          "en":"4088600282848"
        }
      ],
      "UNMAPPED":[
        {
          "en":"ZORBA DELICACIES LTD"
        },
        {
          "en":"FSC logo"
        },
        {
          "en":"289.000000"
        },
        {
          "en":"18073"
        },
        {
          "en":"709102"
        },
        {
          "en":"403094"
        }
      ],
      "NUTRITION_FACTS":[
        {
          "Energy":[
            {
              "Value":{
                "en":"1010"
              }
            },
            {
              "Value":{
                "en":"505"
              }
            },
            {
              "Value":{
                "en":"245"
              }
            },
            {
              "Value":{
                "en":"122"
              }
            },
            {
              "PDV":{
                "en":"6%"
              }
            }
          ],
          "Fat":[
            {
              "Value":{
                "en":"23.8"
              }
            },
            {
              "Value":{
                "en":"11.9"
              }
            },
            {
              "PDV":{
                "en":"17%"
              }
            }
          ],
          "Saturated Fat":[
            {
              "Value":{
                "en":"7.7"
              }
            },
            {
              "Value":{
                "en":"3.9"
              }
            },
            {
              "PDV":{
                "en":"19%"
              }
            }
          ],
          "Carbohydrate":[
            {
              "Value":{
                "en":"5.4"
              }
            },
            {
              "Value":{
                "en":"2.7"
              }
            }
          ],
          "Sugar":[
            {
              "Value":{
                "en":"2.2"
              }
            },
            {
              "Value":{
                "en":"1.1"
              }
            },
            {
              "PDV":{
                "en":"1%"
              }
            }
          ],
          "Fibre":[
            {
              "Value":{
                "en":"0.5"
              }
            },
            {
              "Value":{
                "en":"0.2"
              }
            }
          ],
          "Protein":[
            {
              "Value":{
                "en":"2.0"
              }
            },
            {
              "Value":{
                "en":"1.0"
              }
            }
          ],
          "Salt":[
            {
              "Value":{
                "en":"0.83"
              }
            },
            {
              "Value":{
                "en":"0.42"
              }
            },
            {
              "PDV":{
                "en":"7%"
              }
            }
          ]
        }
      ]
    },
    "8":{
      "BRAND_NAME":[
        {
          "en":"THE DELI"
        }
      ],
      "UNMAPPED":[
        {
          "en":"No"
        },
        {
          "en":"N/A"
        },
        {
          "en":"N/A"
        },
        {
          "en":"No"
        },
        {
          "en":"N/A"
        },
        {
          "en":"N/A"
        },
        {
          "en":"N/A"
        },
        {
          "pl":"Tray: Recycle / Sleeve: Recycle / Film: Don't Recycle /"
        },
        {
          "en":"PTR96 Multipack Tray (No); PES28 Multipack Film (No); 105670 Sleeve (No);"
        }
      ],
      "GENERIC_NAME":[
        {
          "en":"Salsa"
        }
      ],
      "FUNCTIONAL_NAME":[
        {
          "en":"Tomato salsa with onion and coriander"
        }
      ],
      "NET_CONTENT_STATEMENT":[
        {
          "en":"100g"
        }
      ],
      "OTHER_INSTRUCTIONS":[
        {
          "en":"Front, bottom right hand corner of pack."
        }
      ],
      "STORAGE_INSTRUCTIONS":[
        {
          "en":"Keep refrigerated below 5°C."
        },
        {
          "en":"Once opened, keep refrigerated and consume within 2 days and by date shown."
        }
      ],
      "MARKETING_CLAIM":[
        {
          "en":"N/A"
        },
        {
          "en":"Suitable for vegetarians (Aldi logo)."
        },
        {
          "en":"No artificial colours or flavourings."
        },
        {
          "en":"new look, improved recipe."
        },
        {
          "en":"Suitable for vegetarians (text only)."
        },
        {
          "en":"FSC/PEFC"
        }
      ],
      "INGREDIENTS_DECLARATION":[
        {
          "fr":"TOMATO (54%), TOMATO PULPA (25%) (Tomatoes, Acidity Regulator: Citric Acid), ONIONS (7%), Tomato Purée, Sugar, Water, Olive Oil, Coriander, Salt, Garlic Purée, Stabiliser: Xanthan Gum; Preservative: Potassium Sorbate."
        }
      ]
    },
    "9":{
      "ALLERGEN_STATEMENT":[
        {
          "en":"Not Applicable"
        }
      ],
      "FUNCTIONAL_NAME":[
        {
          "en":"MULTIPACK DIPS - TEX MEX SELECTION D"
        }
      ],
      "GTIN_HEADER":[
        {
          "en":"4088600282848"
        }
      ],
      "UNMAPPED":[
        {
          "en":"ZORBA DELICACIES LTD"
        },
        {
          "en":"2D barcode"
        },
        {
          "en":"289.000000"
        },
        {
          "en":"18073"
        },
        {
          "en":"709102"
        },
        {
          "en":"403096"
        },
        {
          "en":"No"
        }
      ],
      "BRAND_NAME":[
        {
          "en":"THE DELI"
        }
      ],
      "GENERIC_NAME":[
        {
          "rw":"Nacho Chilli Cheese Dip"
        }
      ],
      "NUTRITION_FACTS":[
        {
          "Energy":[
            {
              "Value":{
                "en":"188"
              }
            },
            {
              "Value":{
                "en":"94"
              }
            },
            {
              "Value":{
                "en":"45"
              }
            },
            {
              "Value":{
                "en":"22"
              }
            },
            {
              "PDV":{
                "en":"1%"
              }
            }
          ],
          "Fat":[
            {
              "Value":{
                "en":"1.0"
              }
            },
            {
              "Value":{
                "en":"0.5"
              }
            },
            {
              "PDV":{
                "en":"&lt;1%"
              }
            }
          ],
          "Saturated Fat":[
            {
              "Value":{
                "en":"0.2"
              }
            },
            {
              "Value":{
                "en":"0.1"
              }
            },
            {
              "PDV":{
                "en":"&lt;1%"
              }
            }
          ],
          "Carbohydrate":[
            {
              "Value":{
                "en":"6.8"
              }
            },
            {
              "Value":{
                "en":"3.4"
              }
            }
          ],
          "Sugar":[
            {
              "Value":{
                "en":"6.4"
              }
            },
            {
              "Value":{
                "en":"3.2"
              }
            },
            {
              "PDV":{
                "en":"4%"
              }
            }
          ],
          "Fibre":[
            {
              "Value":{
                "en":"2.2"
              }
            },
            {
              "Value":{
                "en":"1.1"
              }
            }
          ],
          "Protein":[
            {
              "Value":{
                "en":"1.0"
              }
            },
            {
              "Value":{
                "en":"0.5"
              }
            }
          ],
          "Salt":[
            {
              "Value":{
                "en":"0.47"
              }
            },
            {
              "Value":{
                "en":"0.23"
              }
            },
            {
              "PDV":{
                "en":"4%"
              }
            }
          ]
        }
      ]
    },
    "10":{
      "FUNCTIONAL_NAME":[
        {
          "en":"A mayonnaise based dip with mature Cheddar cheese, onions and green jalapeño peppers"
        }
      ],
      "UNMAPPED":[
        {
          "en":"N/A"
        },
        {
          "en":"N/A"
        },
        {
          "en":"No"
        },
        {
          "en":"Not suitable for freezing."
        },
        {
          "en":"N/A"
        },
        {
          "en":"N/A"
        },
        {
          "pl":"Tray: Recycle / Sleeve: Recycle / Film: Don't Recycle /"
        },
        {
          "en":"PTR96 Multipack Tray (No); PES28 Multipack Film (No); 105670 Sleeve (No);"
        }
      ],
      "NET_CONTENT_STATEMENT":[
        {
          "en":"100g"
        }
      ],
      "OTHER_INSTRUCTIONS":[
        {
          "en":"Bottom, right hand corner of pack."
        }
      ],
      "STORAGE_INSTRUCTIONS":[
        {
          "en":"Keep refrigerated below 5°C."
        },
        {
          "en":"Once opened, keep refrigerated and consume within 2 days and by date shown."
        }
      ],
      "MARKETING_CLAIM":[
        {
          "en":"N/A."
        },
        {
          "mt":"Chilli Rating - Mild (One Chilli Symbol)."
        },
        {
          "en":"No artificial colours or flavourings."
        },
        {
          "en":"Suitable for vegetarians (text only)."
        },
        {
          "en":"Suitable for vegetarians (Aldi logo)."
        },
        {
          "en":"new look, improved recipe."
        },
        {
          "en":"FSC/PEFC"
        }
      ]
    },
    "11":{
      "INGREDIENTS_DECLARATION":[
        {
          "la":"MAYONNAISE (69%) (Water, Rapeseed Oil, Cornflour, Spirit Vinegar, Whole &lt;b&gt;Egg&lt;/b&gt; Powder, Sugar, Salt), WHITE ONIONS (8%), MATURE CHEDDAR CHEESE 8% (&lt;b&gt;Milk&lt;/b&gt;), Tomato Purée, Water, GREEN JALAPEÑO PEPPER (2%) (Jalapeño Peppers, Water, Sugar Cane Vinegar, Salt, Firming Agent: Calcium Chloride), Sugar, Concentrated Lemon Juice, Cornflour, Garlic Purée, CHILLI SAUCE (0.5%) [Red Chilli Paste (Chilli Peppers, Salt, Acid: Acetic Acid; Preservative: Potassium Sorbate), Red Chilli Puree (Red Bell Pepper, Salt, Chilli Peppers), Salt, Preservative: Acetic Acid; Water, Antioxidant: Citric Acid], Coriander, Oregano, Black Pepper, Turmeric Powder, Preservative: Potassium Sorbate."
        }
      ],
      "ALLERGEN_STATEMENT":[
        {
          "nl":"For allergens, see ingredients in &lt;b&gt;bold&lt;/b&gt;."
        }
      ],
      "NUTRITION_FACTS":[
        {
          "Energy":[
            {
              "Value":{
                "en":"893"
              }
            },
            {
              "Value":{
                "en":"446"
              }
            },
            {
              "Value":{
                "en":"215"
              }
            },
            {
              "Value":{
                "en":"108"
              }
            },
            {
              "PDV":{
                "en":"5%"
              }
            }
          ],
          "Fat":[
            {
              "Value":{
                "en":"18.1"
              }
            },
            {
              "Value":{
                "en":"9.0"
              }
            },
            {
              "PDV":{
                "en":"13%"
              }
            }
          ],
          "Saturated Fat":[
            {
              "Value":{
                "en":"2.8"
              }
            },
            {
              "Value":{
                "en":"1.4"
              }
            },
            {
              "PDV":{
                "en":"7%"
              }
            }
          ],
          "Carbohydrate":[
            {
              "Value":{
                "en":"9.7"
              }
            },
            {
              "Value":{
                "en":"4.8"
              }
            }
          ],
          "Sugar":[
            {
              "Value":{
                "en":"3.9"
              }
            },
            {
              "Value":{
                "en":"2.0"
              }
            },
            {
              "PDV":{
                "en":"2%"
              }
            }
          ],
          "Fibre":[
            {
              "Value":{
                "en":"0.6"
              }
            },
            {
              "Value":{
                "en":"0.3"
              }
            }
          ],
          "Protein":[
            {
              "Value":{
                "en":"3.2"
              }
            },
            {
              "Value":{
                "en":"1.6"
              }
            }
          ],
          "Salt":[
            {
              "Value":{
                "en":"0.78"
              }
            },
            {
              "Value":{
                "en":"0.39"
              }
            },
            {
              "PDV":{
                "en":"7%"
              }
            }
          ]
        }
      ]
    }
  }
}


def aldi_pdf_main(input_file,pdf):
    return  response["file.pdf"]
