sample_response = {'1':{'FUNCTIONAL_NAME': [{'de': 'Continental\n'}],
 'BRAND_NAME': [{'en': 'Side Dish\n'}],
 'SUB_BRAND_NAME': [{'en': 'Core Rice Standard \n'}],
 'PRODUCT_NAME': [{'en': '<b>Cheesy</b>\n'}],
 'NET_CONTENT_STATEMENT': [{'en': '125g e'}],
 'LEGAL_PRODUCT NAME': [{'en': 'Seasoned Rice\n'}],
 'LOCATION_OF_ORIGIN': [{'en': 'Made in Australia from at least 89% Australian ingredients\n'}],
 'STORAGE_INSTRUCTIONS': [{'en': 'Store in a cool, dry place.\n'}],
 'NUTRITION FACTS': [{'Energy': [{'Value': {'en': '1059kJ'}},
    {'Value': {'en': '1643kJ'}},
    {'Value': {'en': '1113kJ'}},
    {'PDV': {'en': '13%'}},
    {'Value': {'en': '554kJ'}}],
   'Calories': [{'Value': {'en': '253Cal'}},
    {'Value': {'en': '393Cal'}},
    {'Value': {'en': '266Cal'}},
    {'Value': {'en': '133Cal'}}],
   'Protein': [{'Value': {'en': '8.5g'}},
    {'Value': {'en': '13.2g'}},
    {'Value': {'en': '8.5g'}},
    {'PDV': {'en': '17%'}},
    {'Value': {'en': '4.2g'}}],
   'fat, total': [{'Value': {'en': '2.4g'}},
    {'Value': {'en': '3.8g'}},
    {'Value': {'en': '3.9g'}},
    {'PDV': {'en': '6%'}},
    {'Value': {'en': '1.9g'}}],
   'saturated': [{'Value': {'en': '1.4g'}},
    {'Value': {'en': '2.2g'}},
    {'Value': {'en': '1.8g'}},
    {'PDV': {'en': '7%'}},
    {'Value': {'en': '0.9g'}}],
   'Carbohydrate': [{'Value': {'en': '48.4g'}},
    {'Value': {'en': '75.1g'}},
    {'Value': {'en': '48.4g'}},
    {'PDV': {'en': '16%'}},
    {'Value': {'en': '24.1g'}}],
   'Sugar': [{'Value': {'en': '2.2g'}},
    {'Value': {'en': '3.4g'}},
    {'Value': {'en': '2.2g'}},
    {'PDV': {'en': '2%'}},
    {'Value': {'en': '1.1g'}}],
   'Fibre': [{'Value': {'en': '0.3g'}},
    {'Value': {'en': '0.4g'}},
    {'Value': {'en': '0.3g'}},
    {'PDV': {'en': '0.9%'}},
    {'Value': {'en': '0.1g'}}],
   'Sodium': [{'Value': {'en': '435mg'}},
    {'Value': {'en': '680mg'}},
    {'Value': {'en': '445mg'}},
    {'PDV': {'en': '19%'}},
    {'Value': {'en': '220mg'}}]}],
 'NUTRITION_TABLE_CONTENT': [{'en': '† When prepared as directed using 310mL water and 4.5g salt reduced margarine. \n* Percentage Daily Intakes are based on an average adult diet of 8700kJ. \n'}],
 'Servings per package': [{'en': '2'}],
 'Serving size': [{'en': 'Approx 64g (dry) makes 201g as prepared†'}]},
 '2': {'PREPARATION_INSTRUCTIONS': [{'en': '<b>Back of pack</b>\n<b>Stove Top - for best results:</b>\n1. Bring 1¼ cups (310mL) hot water, 1 teaspoon salt reduced margarine and Seasoned Rice pack contents to the boil, stirring.\n2. Cover and simmer for 10 minutes or until water is absorbed and rice is cooked. Remove from heat. Stir, replace lid and stand for 2 minutes.\n<b>Microwave (1000W) - cooking times may vary</b>\n1. Combine 1½ cups (375mL) hot water, 1 teaspoon salt reduced margarine and Seasoned Rice pack contents in a microwave safe bowl.\n2. Cover and cook on HIGH for 8-10 minutes or until water is absorbed and rice is cooked. Stir, replace cover and stand for 2 minutes before serving.\nCaution: Bowl and rice will be HOT.\n<b>Cheesy Broccoli, Pea & Ham Rice</b>\nServes 2\nPrep Time: 10 minutesCook Time: 15 minutes\n125g packet Continental Cheesy Rice⅓ cup chopped shaved leg ham2 cups (200g) chopped broccoli florets1 ¼ cups (310mL) hot water½ cup frozen baby peas, thawed2 tablespoons shredded parmesan cheese\n1. Place rice packet contents, ham, broccoli and water in a saucepan. Bring to the boil, stirring. Cover, reduce heat and simmer for 10 minutes. \n2. Stir in peas. Cover and cook for a further 2 minutes or until water is absorbed and rice is cooked. Remove from heat. Stir, cover and stand for 2 minutes. \n3. Divide among serving bowls. Sprinkle with parmesan cheese. Serve.\n'}],
 'INGREDIENTS_DECLARATION': [{'en': 'OUR INGREDIENTS…\nRice (83%), <b>cheese</b> powder (5.5%), skim <b>milk</b> powder, yeast extract, salt, natural flavours (contain <b>milk</b>), onion powder, mineral salt (potassium chloride), chives, vegetable oil, natural colours (carotene, carmine), maltodextrin. \nContains naturally occurring glutamates.\n'}],
 'ALLERGEN_STATEMENT': [{'en': 'ANY ALLERGIES?\n<b>Contains milk.</b>May contain wheat, soybeans, peanuts, tree nuts, egg, sesame, fish, crustacea and lupin.\n'}]}}