name: SGK_AI_Dev_CI_CD_Pipeline

on:
  push:
    branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
      with:
          clean: true

    #- name: Set up Python ${{ matrix.python-version }}
     # uses: actions/setup-python@v3
      #with:
       # python-version: ${{ matrix.python-version }}
        
    #- name: pulling code from github repo
      #run: git pull https://${GITHUB_TOKEN}@github.com/vj-kanagaraj/SGK-AI_DEV.git
      #run: git pull origin master

    - name: find the username
      run: whoami
      
    - name: find the pwd
      run: pwd
      
    #- name: set remote url
     # run: git remote set-url origin ssh://git@ssh.github.com:443/vj-kanagaraj/SGK-AI_DEV.git

    - name: fetch remote url
      run: git remote -v

    - name: checking git status
      run: git status
      
    - name: Deploy to Linux Server
      run: git pull origin master
      #run: git fetch --all
      
    - name: change directory
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh-strict: 'no'
        script: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "sudo systemctl restart gunicorn"
      
#     - name: Install Dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt
#     - name: Run Tests
#       run: |
#         python manage.py test
