name: SGK_AI_Dev_CI_CD_Pipeline

on:
  push:
    branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2

    #- name: Set up Python ${{ matrix.python-version }}
     # uses: actions/setup-python@v3
      #with:
       # python-version: ${{ matrix.python-version }}
        
    #- name: pulling code from github repo
      #run: git pull https://${GITHUB_TOKEN}@github.com/vj-kanagaraj/SGK-AI_DEV.git
      #run: git pull origin master
      
    - name: Deploy to Linux Server
      run: |
          ssh vijay@172.28.42.150  "cd doc_extractor/ && git pull origin master"
      
#     - name: Install Dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt
#     - name: Run Tests
#       run: |
#         python manage.py test
