name: SGK_AI_Dev_CI_CD_Pipeline

on:
  push:
    branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6]

    steps:
    - name: removing all pycache files from server location
      run: sudo find /home/vijay/doc_extractor/actions-runner/sgk-ai-dev/SGK-AI_DEV/SGK-AI_DEV -type d -name "__pycache__" -exec chmod 777 {} +
    
    - uses: actions/checkout@v2
      with:
          clean: true

    #- name: Set up Python ${{ matrix.python-version }}
     # uses: actions/setup-python@v3
      #with:
       # python-version: ${{ matrix.python-version }}

    - name: find the username
      run: whoami
      
    - name: find the pwd
      run: pwd
      
    - name: fetch remote url
      run: git remote -v

    - name: checking git status
      run: git status
      
    - name: Deploy to Linux Server
      run: git pull origin master
      #run: git fetch --all
      
    - name: restart gunicorn
      run: sudo systemctl restart gunicorn.service
      
#     - name: Install Dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt
#     - name: Run Tests
#       run: |
#         python manage.py test
